In [165]:
batch = 2
num = 1
intere_num =4
indices_top = torch.randint(0,5,(batch,num))
indicex_K = torch.randint(0,5,(batch,intere_num))

In [166]:
indices_top,indicex_K

(tensor([[0],
         [1]]), tensor([[2, 0, 3, 1],
         [3, 4, 4, 4]]))

In [167]:
indicex_K.shape[0]

2

In [168]:
x = indices_top.unsqueeze(-1).repeat(1,1,1,intere_num).reshape(batch,-1)
x

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1]])

In [169]:
y = indicex_K.repeat(1,1,num).reshape(batch,-1)
y

tensor([[2, 0, 3, 1],
        [3, 4, 4, 4]])

In [170]:
coordinate = [[a,b] for a,b in zip(x, y)]
coordinate

[[tensor([0, 0, 0, 0]), tensor([2, 0, 3, 1])],
 [tensor([1, 1, 1, 1]), tensor([3, 4, 4, 4])]]

In [171]:
state_matrix = torch.rand(5,5)
state_matrix

tensor([[0.0038, 0.3236, 0.3759, 0.8879, 0.3769],
        [0.6577, 0.1867, 0.5111, 0.2980, 0.2138],
        [0.0371, 0.0204, 0.9866, 0.8967, 0.3042],
        [0.7230, 0.5741, 0.8102, 0.5139, 0.4177],
        [0.5401, 0.5997, 0.4795, 0.1747, 0.4590]])

In [172]:
[state_matrix[co].reshape(num,-1).sum(dim=-1) for co in coordinate]

[tensor([1.5912]), tensor([0.9395])]

In [173]:
torch.cat([state_matrix[co].reshape(num,-1).sum(dim=-1) for co in coordinate]).reshape(batch,-1)

tensor([[1.5912],
        [0.9395]])

In [1]:
import torch

In [13]:
indices_K = torch.tensor([[1,2,3],[4,5,6]])
hitted_idx = torch.tensor([1,0])

In [14]:
indices_K[hitted_idx]

tensor([[4, 5, 6],
        [1, 2, 3]])

In [15]:
torch.tensor([indices_K[a,b] for a,b in enumerate(hitted_idx)])

tensor([2, 4])

In [24]:
indices_K[[0,1],[1,0]]

tensor([2, 6])

In [68]:
hitted_idx = hitted_idx.reshape(-1,1).repeat(1,3)
hitted_idx

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [69]:
torch.cat([torch.cat([a,b]) for a,b in zip(indices_K, hitted_idx)])

tensor([1, 2, 3, 1, 1, 1, 4, 5, 6, 1, 1, 1])

In [72]:
coordinate = torch.cat([torch.cat([a,b]).reshape(2,-1) for a,b in zip(indices_K, hitted_idx)]).reshape(-1,2,3)
coordinate

tensor([[[1, 2, 3],
         [1, 1, 1]],

        [[4, 5, 6],
         [1, 1, 1]]])

In [73]:
crf = torch.rand([10,10])
crf

tensor([[0.8992, 0.2708, 0.9456, 0.4589, 0.2460, 0.4221, 0.0032, 0.1878, 0.8658,
         0.1525],
        [0.5863, 0.5381, 0.4096, 0.6247, 0.5890, 0.5427, 0.9217, 0.2185, 0.2247,
         0.5942],
        [0.9760, 0.1699, 0.7436, 0.7046, 0.2264, 0.9429, 0.8133, 0.7484, 0.8475,
         0.8991],
        [0.6667, 0.0898, 0.3281, 0.9240, 0.2775, 0.7245, 0.1304, 0.9007, 0.0738,
         0.9207],
        [0.2720, 0.9936, 0.6298, 0.7130, 0.2564, 0.6909, 0.8498, 0.5069, 0.7609,
         0.4941],
        [0.2214, 0.7662, 0.4298, 0.2983, 0.9334, 0.8935, 0.9072, 0.8236, 0.4182,
         0.8915],
        [0.4789, 0.6074, 0.1716, 0.9682, 0.5670, 0.7137, 0.1155, 0.5780, 0.4163,
         0.1845],
        [0.6600, 0.7084, 0.0840, 0.4456, 0.3727, 0.0399, 0.7062, 0.0883, 0.1861,
         0.6693],
        [0.8065, 0.0205, 0.1175, 0.6070, 0.6301, 0.0767, 0.6143, 0.0519, 0.5735,
         0.7901],
        [0.8914, 0.5336, 0.7749, 0.5669, 0.9348, 0.8793, 0.5937, 0.9090, 0.0525,
         0.8439]])

In [77]:
crf[coordinate[0].numpy().tolist()]

tensor([0.5381, 0.1699, 0.0898])

In [78]:
coordinate = coordinate.cpu().numpy().tolist()

In [83]:
torch.cat([crf[co] for co in coordinate]).reshape(-1,3)

tensor([[0.5381, 0.1699, 0.0898],
        [0.9936, 0.7662, 0.6074]])

In [84]:
torch.cat([crf[co] for co in coordinate]).reshape(-1,3).sum(dim=1)

tensor([0.7978, 2.3671])

In [2]:
from utils import Data_Read
from Config import Config
config = Config()
config.datasetInfo()

In [3]:
train_lists, test_x, test_y = Data_Read(config)

In [6]:
train_lists[1]

array([[25909, 38756, 44804, 54540, 56212, 39989],
       [56212, 38756,  2890, 44804, 47381, 54540],
       [47381, 25909,  2890, 44804, 54540, 56212],
       ...,
       [32544, 41386, 18642, 60271, 18701, 37261],
       [60476, 37225, 47386, 13732, 46591,  1391],
       [25794, 60468, 33344, 34858, 13382, 42266]])

In [8]:
seq = train_lists[2][2]
seq

array([38756, 47381, 25909, 54540,  2890, 44804, 56212])

In [20]:
seq = [x for x in range(6)]
seq

[0, 1, 2, 3, 4, 5]

In [21]:
window = 4

In [22]:
for i, item in enumerate(seq):
    if i>0:
        l = min(i,window)
        for j in range(l):
            print("{} {} ".format(item,seq[i-1-j]))
        

1 0 
2 1 
2 0 
3 2 
3 1 
3 0 
4 3 
4 2 
4 1 
4 0 
5 4 
5 3 
5 2 
5 1 


In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [24]:
embed_layer = nn.Embedding(4,10)

In [31]:
e1 = embed_layer(torch.tensor(1))
e2 = embed_layer(torch.tensor(2))

In [35]:
e1,e2

(tensor([-0.0404,  1.0936, -1.1947, -0.0090,  0.9085,  0.6575, -0.4485,  1.6211,
         -1.2566, -0.1157], grad_fn=<EmbeddingBackward>),
 tensor([-0.9740,  0.2802,  0.3881,  1.9925,  0.3055, -1.8050, -0.0507,  0.7508,
          0.9224,  0.2238], grad_fn=<EmbeddingBackward>))

In [36]:
e1=torch.tensor([2,3,4,5])
e2=torch.tensor([1,0,0,1])

In [37]:
torch.einsum("i,i",e1,e2)

tensor(7)

In [42]:
torch.tensor(1.)

tensor(1.)

In [56]:
co_bias = nn.Parameter(torch.randn(10))

In [57]:
co_bias

Parameter containing:
tensor([ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
        -0.2277, -2.7700], requires_grad=True)

In [58]:
co_bias.repeat(5,1)

tensor([[ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
         -0.2277, -2.7700],
        [ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
         -0.2277, -2.7700],
        [ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
         -0.2277, -2.7700],
        [ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
         -0.2277, -2.7700],
        [ 0.2929, -0.6695,  1.0150, -0.1858, -0.1017,  0.0922,  1.7807,  0.0423,
         -0.2277, -2.7700]], grad_fn=<RepeatBackward>)

In [59]:
co_bias.repeat(5,1).transpose(0,1)

tensor([[ 0.2929,  0.2929,  0.2929,  0.2929,  0.2929],
        [-0.6695, -0.6695, -0.6695, -0.6695, -0.6695],
        [ 1.0150,  1.0150,  1.0150,  1.0150,  1.0150],
        [-0.1858, -0.1858, -0.1858, -0.1858, -0.1858],
        [-0.1017, -0.1017, -0.1017, -0.1017, -0.1017],
        [ 0.0922,  0.0922,  0.0922,  0.0922,  0.0922],
        [ 1.7807,  1.7807,  1.7807,  1.7807,  1.7807],
        [ 0.0423,  0.0423,  0.0423,  0.0423,  0.0423],
        [-0.2277, -0.2277, -0.2277, -0.2277, -0.2277],
        [-2.7700, -2.7700, -2.7700, -2.7700, -2.7700]],
       grad_fn=<TransposeBackward0>)

In [49]:
type(embed_layer.weight)

torch.nn.parameter.Parameter

In [50]:
type(co_bias)

torch.nn.parameter.Parameter

In [61]:
import numpy as np

In [62]:
matr = np.random.rand(4,4)
m = 0.5
matr

array([[0.67133267, 0.70346716, 0.54755072, 0.60374291],
       [0.12035645, 0.4792099 , 0.06570049, 0.91839773],
       [0.37675805, 0.46255179, 0.68269883, 0.43839234],
       [0.12081551, 0.15161369, 0.97321902, 0.8758381 ]])

In [63]:
min(1.0, matr/m)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [67]:
(matr/m),np.clip((matr/m),a_min=0, a_max=1.0)

(array([[1.34266534, 1.40693432, 1.09510145, 1.20748582],
        [0.2407129 , 0.9584198 , 0.13140099, 1.83679546],
        [0.75351611, 0.92510359, 1.36539767, 0.87678468],
        [0.24163101, 0.30322739, 1.94643803, 1.75167621]]),
 array([[1.        , 1.        , 1.        , 1.        ],
        [0.2407129 , 0.9584198 , 0.13140099, 1.        ],
        [0.75351611, 0.92510359, 1.        , 0.87678468],
        [0.24163101, 0.30322739, 1.        , 1.        ]]))

In [68]:
np1 = np.array([[1,1],[1,0]])
np2 = np.array([[1,2],[3,4]])
ten1 = torch.tensor([[1,2],[3,4]])

In [71]:
np1+ten1

TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'Tensor'

In [73]:
type(min(torch.tensor(1.0), 0.5))

float

In [74]:
ten1.pow(2)

tensor([[ 1,  4],
        [ 9, 16]])

In [84]:
co_matrix = np.array([[1,2,3],[2,3,4],[5,3,1]])
co_bias = nn.Parameter(torch.randn(3)) 
co_matrix,co_bias

(array([[1, 2, 3],
        [2, 3, 4],
        [5, 3, 1]]), Parameter containing:
 tensor([-0.8213, -0.7490,  0.4412], requires_grad=True))

In [85]:
item_embed = nn.Embedding(3,5)
item_embed.weight

Parameter containing:
tensor([[ 0.3796, -1.7199,  1.4499, -0.0999, -0.0561],
        [ 1.0369,  0.9192, -0.2725, -0.5627,  1.7717],
        [-0.9230, -0.5910,  0.0739, -0.7949,  0.1797]], requires_grad=True)

In [86]:
embed_sim = torch.einsum("ik,jk -> ij",item_embed.weight,item_embed.weight) 

In [87]:
embed_sim

tensor([[ 5.2176, -1.6257,  0.8425],
        [-1.6257,  5.4499, -0.7547],
        [ 0.8425, -0.7547,  1.8708]], grad_fn=<ViewBackward>)

In [89]:
bias  = co_bias.repeat(3,1) + co_bias.repeat(3,1).transpose(0,1)
bias

tensor([[-1.6427, -1.5703, -0.3801],
        [-1.5703, -1.4980, -0.3078],
        [-0.3801, -0.3078,  0.8824]], grad_fn=<AddBackward0>)

In [91]:
weight = np.clip(co_matrix/2,a_min=0, a_max=1.0)
weight

array([[0.5, 1. , 1. ],
       [1. , 1. , 1. ],
       [1. , 1. , 0.5]])

In [97]:
loss = torch.tensor(weight) * ((embed_sim + bias - torch.tensor(co_matrix)).pow(2))
loss

tensor([[ 3.3151, 26.9983,  6.4393],
        [26.9983,  0.9063, 25.6289],
        [20.5896, 16.5039,  1.5369]], dtype=torch.float64,
       grad_fn=<MulBackward0>)

In [98]:
torch.sum(loss)

tensor(128.9166, dtype=torch.float64, grad_fn=<SumBackward0>)

128.8