In [1]:
import torch

In [36]:
batch = 2
intere_num = 3
num = 4
embed_dim = 5
Candidate_num = 10
indicex_K = torch.randint(0,Candidate_num,[batch,intere_num])
item_embeds = torch.randn(batch,num,embed_dim)
Candidate_pool = torch.randn(Candidate_num, embed_dim)
state_matrix = torch.randn(Candidate_num, Candidate_num)

In [38]:
print("indicex_K")
print(indicex_K)
print("item_embeds")
print(item_embeds)
print("Candidate_pool")
print(Candidate_pool)
print("state_matrix")
print(state_matrix)

indicex_K
tensor([[3, 6, 9],
        [5, 2, 1]])
item_embeds
tensor([[[ 0.7193,  0.6754,  2.0429,  0.2715,  0.3861],
         [ 1.3963,  1.6430,  0.3876, -0.3496, -0.0214],
         [-0.2215, -0.0318, -0.4582, -0.9384, -0.1939],
         [ 0.1414, -1.5775,  1.1119, -0.9933, -0.9798]],

        [[ 0.4813,  1.1338,  1.1965, -0.1071, -0.5052],
         [ 0.3751, -0.3792,  0.0373,  0.1905, -0.9154],
         [ 0.1515,  2.0769,  0.2994, -0.4514, -0.1479],
         [ 0.5569, -0.3140,  0.4510,  0.7239, -0.1481]]])
Candidate_pool
tensor([[-0.7642, -0.7364, -0.7309, -1.3110, -2.3264],
        [-0.1302, -0.1418, -0.5042,  0.9560, -0.9158],
        [ 0.2901,  1.9039, -1.7933, -0.9856,  0.7402],
        [ 0.0398,  0.7728,  0.6016, -0.0664, -1.4816],
        [-2.2647,  0.0117,  0.8231,  1.8155,  0.9940],
        [ 0.9039, -1.0636,  1.8002,  1.1506, -1.7046],
        [-0.1681, -0.7014, -0.7217, -0.5581, -1.2023],
        [ 0.1384, -0.3642, -0.7467,  0.0617, -0.2390],
        [-0.8786,  1.5281,  0.73

In [47]:
batch = item_embeds.shape[0]
num = item_embeds.shape[1]

In [55]:
# 计算每个embedding与Candidate_pool中vec的相似度
Candidate_sim_score = torch.einsum('ijd, kd -> ijk', item_embeds, Candidate_pool) #[batch,num,Candidate_num]
Candidate_sim_score

tensor([[[-3.7942, -1.3134, -2.1508,  1.1895,  0.9372,  3.2637, -2.6846,
          -1.7474,  2.4039,  1.2161],
         [-2.0521, -0.9248,  3.1668,  1.6133, -3.4798, -0.1534, -1.4460,
          -0.7109,  0.8909,  3.1677],
         [ 2.2088, -0.4552,  1.4783,  0.0406, -1.7721, -1.7404,  1.1470,
           0.3115, -2.0014,  0.7748],
         [ 3.8225, -0.4078, -4.7025,  0.9731, -2.2006,  4.3345,  2.0126,
          -0.0633, -3.5809, -2.4889]],

        [[-0.7614, -0.4664, -0.1158,  2.3707, -0.7884,  2.1209, -1.0724,
          -1.1255,  2.0158,  0.2218],
         [ 1.8452,  1.0065, -1.5454,  1.0879, -1.3873,  2.5890,  1.1703,
           0.3928, -0.4492, -2.3412],
         [-0.9282, -0.7612,  3.7966,  2.0402, -1.0388, -1.8003, -1.2685,
          -0.9514,  2.3935,  2.3550],
         [-1.1286,  0.5723, -2.0683,  0.2220,  0.2736,  2.7346, -0.4249,
          -0.0652,  0.7795, -1.2666]]])

In [56]:
# 对每个batch内的得分，降序排列
sorted_score, indices = torch.sort(Candidate_sim_score, descending = True)  #[batch, num,Candidate_num]
sorted_score,indices

(tensor([[[ 3.2637,  2.4039,  1.2161,  1.1895,  0.9372, -1.3134, -1.7474,
           -2.1508, -2.6846, -3.7942],
          [ 3.1677,  3.1668,  1.6133,  0.8909, -0.1534, -0.7109, -0.9248,
           -1.4460, -2.0521, -3.4798],
          [ 2.2088,  1.4783,  1.1470,  0.7748,  0.3115,  0.0406, -0.4552,
           -1.7404, -1.7721, -2.0014],
          [ 4.3345,  3.8225,  2.0126,  0.9731, -0.0633, -0.4078, -2.2006,
           -2.4889, -3.5809, -4.7025]],
 
         [[ 2.3707,  2.1209,  2.0158,  0.2218, -0.1158, -0.4664, -0.7614,
           -0.7884, -1.0724, -1.1255],
          [ 2.5890,  1.8452,  1.1703,  1.0879,  1.0065,  0.3928, -0.4492,
           -1.3873, -1.5454, -2.3412],
          [ 3.7966,  2.3935,  2.3550,  2.0402, -0.7612, -0.9282, -0.9514,
           -1.0388, -1.2685, -1.8003],
          [ 2.7346,  0.7795,  0.5723,  0.2736,  0.2220, -0.0652, -0.4249,
           -1.1286, -1.2666, -2.0683]]]),
 tensor([[[5, 8, 9, 3, 4, 1, 7, 2, 6, 0],
          [9, 2, 3, 8, 5, 7, 1, 6, 0, 4],
      

In [57]:
# 取 top 1
indices_top = indices[:, : , 0]  #[batch, num] 
indices_top

tensor([[5, 9, 0, 5],
        [3, 5, 2, 5]])

In [58]:
x = indices_top.unsqueeze(-1).repeat(1,1,1,intere_num).reshape(batch,-1)
y = indicex_K.repeat(1,1,num).reshape(batch,-1)
x,y

(tensor([[5, 5, 5, 9, 9, 9, 0, 0, 0, 5, 5, 5],
         [3, 3, 3, 5, 5, 5, 2, 2, 2, 5, 5, 5]]),
 tensor([[3, 6, 9, 3, 6, 9, 3, 6, 9, 3, 6, 9],
         [5, 2, 1, 5, 2, 1, 5, 2, 1, 5, 2, 1]]))

In [59]:
coordinate = [[a,b] for a,b in zip(x, y)]
coordinate

[[tensor([5, 5, 5, 9, 9, 9, 0, 0, 0, 5, 5, 5]),
  tensor([3, 6, 9, 3, 6, 9, 3, 6, 9, 3, 6, 9])],
 [tensor([3, 3, 3, 5, 5, 5, 2, 2, 2, 5, 5, 5]),
  tensor([5, 2, 1, 5, 2, 1, 5, 2, 1, 5, 2, 1])]]

In [53]:
crf_score = torch.cat([state_matrix[co].reshape(num,-1).sum(dim=-1) for co in coordinate]).reshape(batch,-1) #[batch,num]

In [54]:
crf_score.shape

torch.Size([2, 4])